services:
  api:
    image: subkey/wms-api:latest
    container_name: wms-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${API_PORT}
      ENV: production
      JWT_SECRET: ${JWT_SECRET}
      # CORS: Separar dominios por comas. Ejemplo: https://mi-frontend.com,http://localhost:3000
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    networks:
      - wms-network

networks:
  wms-network:
    driver: bridge
