services:
  api:
    image: subkey/wms-api:latest
    container_name: wms-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${API_PORT}
      ENV: production
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      COOKIE_SECURE: ${COOKIE_SECURE}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - wms-network
    depends_on:
      - redis

  redis:
    image: redis:8-alpine
    container_name: wms-redis
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - wms-network

networks:
  wms-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
